/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as VolunteerIndexRouteImport } from './routes/volunteer/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as VolunteerCheckInRouteImport } from './routes/volunteer/check-in'
import { Route as VolunteerAnnouncementsRouteImport } from './routes/volunteer/announcements'
import { Route as AdminVolunteersRouteImport } from './routes/admin/volunteers'
import { Route as AdminVerificationsRouteImport } from './routes/admin/verifications'
import { Route as AdminTournamentsRouteImport } from './routes/admin/tournaments'
import { Route as AdminSponsorsRouteImport } from './routes/admin/sponsors'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRegistrationsRouteImport } from './routes/admin/registrations'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminFormBuilderRouteImport } from './routes/admin/form-builder'
import { Route as AdminFinanceRouteImport } from './routes/admin/finance'
import { Route as AdminControlCenterRouteImport } from './routes/admin/control-center'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminCertificatesRouteImport } from './routes/admin/certificates'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicSponsorsRouteImport } from './routes/_public/sponsors'
import { Route as PublicRulesRouteImport } from './routes/_public/rules'
import { Route as PublicResultsRouteImport } from './routes/_public/results'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicPrizeStructureRouteImport } from './routes/_public/prize-structure'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicGalleryRouteImport } from './routes/_public/gallery'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as PublicTournamentsIndexRouteImport } from './routes/_public/tournaments.index'
import { Route as VCheckinTokenRouteImport } from './routes/v/checkin.$token'
import { Route as PublicTournamentsSlugRouteImport } from './routes/_public/tournaments.$slug'
import { Route as PublicPlayersSlugRouteImport } from './routes/_public/players.$slug'
import { Route as PublicGTokenRouteImport } from './routes/_public/g.$token'
import { Route as PublicRegisterSuccessIdRouteImport } from './routes/_public/register.success.$id'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerIndexRoute = VolunteerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VolunteerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const VolunteerCheckInRoute = VolunteerCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerAnnouncementsRoute = VolunteerAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => VolunteerRoute,
} as any)
const AdminVolunteersRoute = AdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationsRoute = AdminVerificationsRouteImport.update({
  id: '/verifications',
  path: '/verifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationsRoute = AdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFormBuilderRoute = AdminFormBuilderRouteImport.update({
  id: '/form-builder',
  path: '/form-builder',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminControlCenterRoute = AdminControlCenterRouteImport.update({
  id: '/control-center',
  path: '/control-center',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSponsorsRoute = PublicSponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRulesRoute = PublicRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResultsRoute = PublicResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrizeStructureRoute = PublicPrizeStructureRouteImport.update({
  id: '/prize-structure',
  path: '/prize-structure',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGalleryRoute = PublicGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTournamentsIndexRoute = PublicTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => PublicRoute,
} as any)
const VCheckinTokenRoute = VCheckinTokenRouteImport.update({
  id: '/v/checkin/$token',
  path: '/v/checkin/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTournamentsSlugRoute = PublicTournamentsSlugRouteImport.update({
  id: '/tournaments/$slug',
  path: '/tournaments/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPlayersSlugRoute = PublicPlayersSlugRouteImport.update({
  id: '/players/$slug',
  path: '/players/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGTokenRoute = PublicGTokenRouteImport.update({
  id: '/g/$token',
  path: '/g/$token',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterSuccessIdRoute = PublicRegisterSuccessIdRouteImport.update({
  id: '/success/$id',
  path: '/success/$id',
  getParentRoute: () => PublicRegisterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/volunteer': typeof VolunteerRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/gallery': typeof PublicGalleryRoute
  '/privacy': typeof PublicPrivacyRoute
  '/prize-structure': typeof PublicPrizeStructureRoute
  '/register': typeof PublicRegisterRouteWithChildren
  '/results': typeof PublicResultsRoute
  '/rules': typeof PublicRulesRoute
  '/sponsors': typeof PublicSponsorsRoute
  '/terms': typeof PublicTermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/control-center': typeof AdminControlCenterRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/form-builder': typeof AdminFormBuilderRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/volunteer/announcements': typeof VolunteerAnnouncementsRoute
  '/volunteer/check-in': typeof VolunteerCheckInRoute
  '/admin/': typeof AdminIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/g/$token': typeof PublicGTokenRoute
  '/players/$slug': typeof PublicPlayersSlugRoute
  '/tournaments/$slug': typeof PublicTournamentsSlugRoute
  '/v/checkin/$token': typeof VCheckinTokenRoute
  '/tournaments/': typeof PublicTournamentsIndexRoute
  '/register/success/$id': typeof PublicRegisterSuccessIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/gallery': typeof PublicGalleryRoute
  '/privacy': typeof PublicPrivacyRoute
  '/prize-structure': typeof PublicPrizeStructureRoute
  '/register': typeof PublicRegisterRouteWithChildren
  '/results': typeof PublicResultsRoute
  '/rules': typeof PublicRulesRoute
  '/sponsors': typeof PublicSponsorsRoute
  '/terms': typeof PublicTermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/control-center': typeof AdminControlCenterRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/form-builder': typeof AdminFormBuilderRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/volunteer/announcements': typeof VolunteerAnnouncementsRoute
  '/volunteer/check-in': typeof VolunteerCheckInRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/volunteer': typeof VolunteerIndexRoute
  '/g/$token': typeof PublicGTokenRoute
  '/players/$slug': typeof PublicPlayersSlugRoute
  '/tournaments/$slug': typeof PublicTournamentsSlugRoute
  '/v/checkin/$token': typeof VCheckinTokenRoute
  '/tournaments': typeof PublicTournamentsIndexRoute
  '/register/success/$id': typeof PublicRegisterSuccessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/volunteer': typeof VolunteerRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/gallery': typeof PublicGalleryRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/prize-structure': typeof PublicPrizeStructureRoute
  '/_public/register': typeof PublicRegisterRouteWithChildren
  '/_public/results': typeof PublicResultsRoute
  '/_public/rules': typeof PublicRulesRoute
  '/_public/sponsors': typeof PublicSponsorsRoute
  '/_public/terms': typeof PublicTermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/control-center': typeof AdminControlCenterRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/form-builder': typeof AdminFormBuilderRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/registrations': typeof AdminRegistrationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/admin/verifications': typeof AdminVerificationsRoute
  '/admin/volunteers': typeof AdminVolunteersRoute
  '/volunteer/announcements': typeof VolunteerAnnouncementsRoute
  '/volunteer/check-in': typeof VolunteerCheckInRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/_public/g/$token': typeof PublicGTokenRoute
  '/_public/players/$slug': typeof PublicPlayersSlugRoute
  '/_public/tournaments/$slug': typeof PublicTournamentsSlugRoute
  '/v/checkin/$token': typeof VCheckinTokenRoute
  '/_public/tournaments/': typeof PublicTournamentsIndexRoute
  '/_public/register/success/$id': typeof PublicRegisterSuccessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/volunteer'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/privacy'
    | '/prize-structure'
    | '/register'
    | '/results'
    | '/rules'
    | '/sponsors'
    | '/terms'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/certificates'
    | '/admin/content'
    | '/admin/control-center'
    | '/admin/finance'
    | '/admin/form-builder'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/sponsors'
    | '/admin/tournaments'
    | '/admin/verifications'
    | '/admin/volunteers'
    | '/volunteer/announcements'
    | '/volunteer/check-in'
    | '/admin/'
    | '/volunteer/'
    | '/g/$token'
    | '/players/$slug'
    | '/tournaments/$slug'
    | '/v/checkin/$token'
    | '/tournaments/'
    | '/register/success/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/privacy'
    | '/prize-structure'
    | '/register'
    | '/results'
    | '/rules'
    | '/sponsors'
    | '/terms'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/certificates'
    | '/admin/content'
    | '/admin/control-center'
    | '/admin/finance'
    | '/admin/form-builder'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/sponsors'
    | '/admin/tournaments'
    | '/admin/verifications'
    | '/admin/volunteers'
    | '/volunteer/announcements'
    | '/volunteer/check-in'
    | '/'
    | '/admin'
    | '/volunteer'
    | '/g/$token'
    | '/players/$slug'
    | '/tournaments/$slug'
    | '/v/checkin/$token'
    | '/tournaments'
    | '/register/success/$id'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/auth'
    | '/volunteer'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/gallery'
    | '/_public/privacy'
    | '/_public/prize-structure'
    | '/_public/register'
    | '/_public/results'
    | '/_public/rules'
    | '/_public/sponsors'
    | '/_public/terms'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/certificates'
    | '/admin/content'
    | '/admin/control-center'
    | '/admin/finance'
    | '/admin/form-builder'
    | '/admin/inventory'
    | '/admin/media'
    | '/admin/registrations'
    | '/admin/settings'
    | '/admin/sponsors'
    | '/admin/tournaments'
    | '/admin/verifications'
    | '/admin/volunteers'
    | '/volunteer/announcements'
    | '/volunteer/check-in'
    | '/_public/'
    | '/admin/'
    | '/volunteer/'
    | '/_public/g/$token'
    | '/_public/players/$slug'
    | '/_public/tournaments/$slug'
    | '/v/checkin/$token'
    | '/_public/tournaments/'
    | '/_public/register/success/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  VolunteerRoute: typeof VolunteerRouteWithChildren
  VCheckinTokenRoute: typeof VCheckinTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/': {
      id: '/volunteer/'
      path: '/'
      fullPath: '/volunteer/'
      preLoaderRoute: typeof VolunteerIndexRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/volunteer/check-in': {
      id: '/volunteer/check-in'
      path: '/check-in'
      fullPath: '/volunteer/check-in'
      preLoaderRoute: typeof VolunteerCheckInRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/announcements': {
      id: '/volunteer/announcements'
      path: '/announcements'
      fullPath: '/volunteer/announcements'
      preLoaderRoute: typeof VolunteerAnnouncementsRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/admin/volunteers': {
      id: '/admin/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminVolunteersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verifications': {
      id: '/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AdminVerificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sponsors': {
      id: '/admin/sponsors'
      path: '/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminSponsorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registrations': {
      id: '/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminRegistrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/form-builder': {
      id: '/admin/form-builder'
      path: '/form-builder'
      fullPath: '/admin/form-builder'
      preLoaderRoute: typeof AdminFormBuilderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/control-center': {
      id: '/admin/control-center'
      path: '/control-center'
      fullPath: '/admin/control-center'
      preLoaderRoute: typeof AdminControlCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sponsors': {
      id: '/_public/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof PublicSponsorsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/rules': {
      id: '/_public/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof PublicRulesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/results': {
      id: '/_public/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof PublicResultsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/prize-structure': {
      id: '/_public/prize-structure'
      path: '/prize-structure'
      fullPath: '/prize-structure'
      preLoaderRoute: typeof PublicPrizeStructureRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gallery': {
      id: '/_public/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof PublicGalleryRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/tournaments/': {
      id: '/_public/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof PublicTournamentsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/v/checkin/$token': {
      id: '/v/checkin/$token'
      path: '/v/checkin/$token'
      fullPath: '/v/checkin/$token'
      preLoaderRoute: typeof VCheckinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/tournaments/$slug': {
      id: '/_public/tournaments/$slug'
      path: '/tournaments/$slug'
      fullPath: '/tournaments/$slug'
      preLoaderRoute: typeof PublicTournamentsSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/players/$slug': {
      id: '/_public/players/$slug'
      path: '/players/$slug'
      fullPath: '/players/$slug'
      preLoaderRoute: typeof PublicPlayersSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/g/$token': {
      id: '/_public/g/$token'
      path: '/g/$token'
      fullPath: '/g/$token'
      preLoaderRoute: typeof PublicGTokenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register/success/$id': {
      id: '/_public/register/success/$id'
      path: '/success/$id'
      fullPath: '/register/success/$id'
      preLoaderRoute: typeof PublicRegisterSuccessIdRouteImport
      parentRoute: typeof PublicRegisterRoute
    }
  }
}

interface PublicRegisterRouteChildren {
  PublicRegisterSuccessIdRoute: typeof PublicRegisterSuccessIdRoute
}

const PublicRegisterRouteChildren: PublicRegisterRouteChildren = {
  PublicRegisterSuccessIdRoute: PublicRegisterSuccessIdRoute,
}

const PublicRegisterRouteWithChildren = PublicRegisterRoute._addFileChildren(
  PublicRegisterRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicGalleryRoute: typeof PublicGalleryRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicPrizeStructureRoute: typeof PublicPrizeStructureRoute
  PublicRegisterRoute: typeof PublicRegisterRouteWithChildren
  PublicResultsRoute: typeof PublicResultsRoute
  PublicRulesRoute: typeof PublicRulesRoute
  PublicSponsorsRoute: typeof PublicSponsorsRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicGTokenRoute: typeof PublicGTokenRoute
  PublicPlayersSlugRoute: typeof PublicPlayersSlugRoute
  PublicTournamentsSlugRoute: typeof PublicTournamentsSlugRoute
  PublicTournamentsIndexRoute: typeof PublicTournamentsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicGalleryRoute: PublicGalleryRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicPrizeStructureRoute: PublicPrizeStructureRoute,
  PublicRegisterRoute: PublicRegisterRouteWithChildren,
  PublicResultsRoute: PublicResultsRoute,
  PublicRulesRoute: PublicRulesRoute,
  PublicSponsorsRoute: PublicSponsorsRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicGTokenRoute: PublicGTokenRoute,
  PublicPlayersSlugRoute: PublicPlayersSlugRoute,
  PublicTournamentsSlugRoute: PublicTournamentsSlugRoute,
  PublicTournamentsIndexRoute: PublicTournamentsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminControlCenterRoute: typeof AdminControlCenterRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminFormBuilderRoute: typeof AdminFormBuilderRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminRegistrationsRoute: typeof AdminRegistrationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSponsorsRoute: typeof AdminSponsorsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  AdminVerificationsRoute: typeof AdminVerificationsRoute
  AdminVolunteersRoute: typeof AdminVolunteersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminControlCenterRoute: AdminControlCenterRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminFormBuilderRoute: AdminFormBuilderRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminRegistrationsRoute: AdminRegistrationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSponsorsRoute: AdminSponsorsRoute,
  AdminTournamentsRoute: AdminTournamentsRoute,
  AdminVerificationsRoute: AdminVerificationsRoute,
  AdminVolunteersRoute: AdminVolunteersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface VolunteerRouteChildren {
  VolunteerAnnouncementsRoute: typeof VolunteerAnnouncementsRoute
  VolunteerCheckInRoute: typeof VolunteerCheckInRoute
  VolunteerIndexRoute: typeof VolunteerIndexRoute
}

const VolunteerRouteChildren: VolunteerRouteChildren = {
  VolunteerAnnouncementsRoute: VolunteerAnnouncementsRoute,
  VolunteerCheckInRoute: VolunteerCheckInRoute,
  VolunteerIndexRoute: VolunteerIndexRoute,
}

const VolunteerRouteWithChildren = VolunteerRoute._addFileChildren(
  VolunteerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  VolunteerRoute: VolunteerRouteWithChildren,
  VCheckinTokenRoute: VCheckinTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
